{"links": {"self": {"href": "data/repositories/hoffmanlab/segway/issues/46/comments/21318953.json"}, "html": {"href": "#!/hoffmanlab/segway/issues/46#comment-21318953"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "title": "`--enforce-coords` results in ERROR: RV 'frameIndex...' has cardinality ..., but current frame value ... too large to store in RV with this cardinality"}, "content": {"raw": "I think enforce-coords is specific to my branch, so I'm not sure this is actually a bug in the trunk.", "markup": "markdown", "html": "<p>I think enforce-coords is specific to my branch, so I'm not sure this is actually a bug in the trunk.</p>", "type": "rendered"}, "created_on": "2015-08-28T15:41:27.223754+00:00", "user": {"display_name": "mlibbrecht", "uuid": "{5386772a-11f2-40a6-922a-1557e4210ce0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5386772a-11f2-40a6-922a-1557e4210ce0%7D"}, "html": {"href": "https://bitbucket.org/%7B5386772a-11f2-40a6-922a-1557e4210ce0%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4f04fb35d1668084963524c0e908eac9d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsM-5.png"}}, "nickname": "mlibbrecht", "type": "user", "account_id": "557058:1c71e8bb-defa-4b90-b75b-f9517c35ceb8"}, "updated_on": null, "type": "issue_comment", "id": 21318953}