{"priority": "minor", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/segway/issues/67/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/segway/issues/67.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/67/watch"}, "comments": {"href": "data/repositories/hoffmanlab/segway/issues/67/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/segway/issues/67/segway-recovery-training-mode-fails-to"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/67/vote"}}, "reporter": {"display_name": "Rachel Chan", "uuid": "{20430f8d-4e6b-48cc-a8d8-c64868bf7e79}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D"}, "html": {"href": "https://bitbucket.org/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4397abec9f84e35f1f235b350984833dd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsRC-1.png"}}, "nickname": "rcwchan", "type": "user", "account_id": "557058:e439e22e-8cfc-4cf1-b090-030d33a0730e"}, "title": "segway recovery (training mode) fails to copy over likelihood files", "component": null, "votes": 0, "watches": 1, "content": {"raw": "While running segway on recovery (training mode), I received this error:\r\n\r\n\r\n```\r\n#!python\r\n\r\nTraceback (most recent call last):\r\n   File \"/mnt/work1/users/home2/rachelc/.local/bin/segway\", line 9, in <module>\r\n     load_entry_point('segway==1.4.1.dev0', 'console_scripts', 'segway')()\r\n   File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2919, in main\r\n     return runner()\r\n   File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2712, in __call__\r\n     self.run(*args, **kwargs)\r\n   File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2679, in run\r\n     self.run_train()\r\n   File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2225, in run_train\r\n     self.finish_train(instance_params, dst_filenames)\r\n   File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2207, in finish_train\r\n     self.proc_train_results(instance_params, dst_filenames)\r\n   File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2332, in proc_train_results\r\n     self.copy_results(name, src_filename, dst_filename)\r\n   File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 1743, in copy_results\r\n     copy2(src_filename, dst_filename)\r\n   File \"/mnt/work1/software/python/2.7/lib/python2.7/shutil.py\", line 128, in copy2\r\n     copyfile(src, dst)\r\n   File \"/mnt/work1/software/python/2.7/lib/python2.7/shutil.py\", line 82, in copyfile\r\n     with open(src, 'rb') as fsrc:\r\n IOError: [Errno 2] No such file or directory: path('/mnt/work1/users/hoffmangroup/rachelc/2016/semisupervised_tests/20160513_1347/results/20160513-1717/K562_5_Track.traindir/likelihood/likelihood.1.ll')\r\n```\r\n\r\n\r\nUpon further investigation, I discovered that in every previous recovery directory, the number of likelihood files declined with recency. For instance, in the earliest recovery directory for this run, there were 10 files (this run was recovered several times). In the second recovery directory, there were again 10, in the next, 8, then 5, then 3, then 0, and 0 again (arriving at the most recent recovery directory). \r\n\r\nMy theory is that the likelihood files are written-to and updated so long as the particular instance (10 instances in this case) is still active. So for the first two runs, instance 0 was still running and so its likelihood file was written to and appeared in the first two runs. Then after that, it did not appear again. Then in the final recovery run, when segway attempts to pick a winner (or do a cumulative analysis or something at the end), it can't find the likelihood files because they were not run during that recovery instance, and errors out. Looking at the files present and missing in each recovery attempt's directory, this seems to be the case.", "markup": "markdown", "html": "<p>While running segway on recovery (training mode), I received this error:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"n\">Traceback</span> <span class=\"p\">(</span><span class=\"n\">most</span> <span class=\"n\">recent</span> <span class=\"n\">call</span> <span class=\"n\">last</span><span class=\"p\">):</span>\n   <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/rachelc/.local/bin/segway&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">9</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"o\">&lt;</span><span class=\"n\">module</span><span class=\"o\">&gt;</span>\n     <span class=\"n\">load_entry_point</span><span class=\"p\">(</span><span class=\"s1\">&#39;segway==1.4.1.dev0&#39;</span><span class=\"p\">,</span> <span class=\"s1\">&#39;console_scripts&#39;</span><span class=\"p\">,</span> <span class=\"s1\">&#39;segway&#39;</span><span class=\"p\">)()</span>\n   <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">2919</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">main</span>\n     <span class=\"k\">return</span> <span class=\"n\">runner</span><span class=\"p\">()</span>\n   <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">2712</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"fm\">__call__</span>\n     <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">run</span><span class=\"p\">(</span><span class=\"o\">*</span><span class=\"n\">args</span><span class=\"p\">,</span> <span class=\"o\">**</span><span class=\"n\">kwargs</span><span class=\"p\">)</span>\n   <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">2679</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">run</span>\n     <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">run_train</span><span class=\"p\">()</span>\n   <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">2225</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">run_train</span>\n     <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">finish_train</span><span class=\"p\">(</span><span class=\"n\">instance_params</span><span class=\"p\">,</span> <span class=\"n\">dst_filenames</span><span class=\"p\">)</span>\n   <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">2207</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">finish_train</span>\n     <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">proc_train_results</span><span class=\"p\">(</span><span class=\"n\">instance_params</span><span class=\"p\">,</span> <span class=\"n\">dst_filenames</span><span class=\"p\">)</span>\n   <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">2332</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">proc_train_results</span>\n     <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">copy_results</span><span class=\"p\">(</span><span class=\"n\">name</span><span class=\"p\">,</span> <span class=\"n\">src_filename</span><span class=\"p\">,</span> <span class=\"n\">dst_filename</span><span class=\"p\">)</span>\n   <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">1743</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">copy_results</span>\n     <span class=\"n\">copy2</span><span class=\"p\">(</span><span class=\"n\">src_filename</span><span class=\"p\">,</span> <span class=\"n\">dst_filename</span><span class=\"p\">)</span>\n   <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/software/python/2.7/lib/python2.7/shutil.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">128</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">copy2</span>\n     <span class=\"n\">copyfile</span><span class=\"p\">(</span><span class=\"n\">src</span><span class=\"p\">,</span> <span class=\"n\">dst</span><span class=\"p\">)</span>\n   <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/software/python/2.7/lib/python2.7/shutil.py&quot;</span><span class=\"p\">,</span> <span class=\"n\">line</span> <span class=\"mi\">82</span><span class=\"p\">,</span> <span class=\"ow\">in</span> <span class=\"n\">copyfile</span>\n     <span class=\"k\">with</span> <span class=\"nb\">open</span><span class=\"p\">(</span><span class=\"n\">src</span><span class=\"p\">,</span> <span class=\"s1\">&#39;rb&#39;</span><span class=\"p\">)</span> <span class=\"k\">as</span> <span class=\"n\">fsrc</span><span class=\"p\">:</span>\n <span class=\"ne\">IOError</span><span class=\"p\">:</span> <span class=\"p\">[</span><span class=\"n\">Errno</span> <span class=\"mi\">2</span><span class=\"p\">]</span> <span class=\"n\">No</span> <span class=\"n\">such</span> <span class=\"nb\">file</span> <span class=\"ow\">or</span> <span class=\"n\">directory</span><span class=\"p\">:</span> <span class=\"n\">path</span><span class=\"p\">(</span><span class=\"s1\">&#39;/mnt/work1/users/hoffmangroup/rachelc/2016/semisupervised_tests/20160513_1347/results/20160513-1717/K562_5_Track.traindir/likelihood/likelihood.1.ll&#39;</span><span class=\"p\">)</span>\n</pre></div>\n\n\n<p>Upon further investigation, I discovered that in every previous recovery directory, the number of likelihood files declined with recency. For instance, in the earliest recovery directory for this run, there were 10 files (this run was recovered several times). In the second recovery directory, there were again 10, in the next, 8, then 5, then 3, then 0, and 0 again (arriving at the most recent recovery directory). </p>\n<p>My theory is that the likelihood files are written-to and updated so long as the particular instance (10 instances in this case) is still active. So for the first two runs, instance 0 was still running and so its likelihood file was written to and appeared in the first two runs. Then after that, it did not appear again. Then in the final recovery run, when segway attempts to pick a winner (or do a cumulative analysis or something at the end), it can't find the likelihood files because they were not run during that recovery instance, and errors out. Looking at the files present and missing in each recovery attempt's directory, this seems to be the case.</p>", "type": "rendered"}, "assignee": null, "state": "new", "version": null, "edited_on": null, "created_on": "2016-05-27T17:09:37.745347+00:00", "milestone": null, "updated_on": "2016-05-30T17:00:53.087805+00:00", "type": "issue", "id": 67}