{"links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/52/comments/20533656.json"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/52/_/diff#comment-20533656"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 52, "links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/52.json"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/52"}}, "title": "Resubmit the mixtures of Gaussians code"}, "content": {"raw": "@rcwchan : \n\nI made some changes that should fix this patch in the case of multiple genomedata archives. Unfortunately, after about 30 minutes of messing with my environment, I could not get this version of Segway working, so I haven't tested these changes. There are almost certainly bugs -- if you're having trouble fixing them, let me know and I'll try to help.\n\nBriefly, here is what I did: The previous patch changed observations.save() to take a Genomedata object as input, and passed the genomedata object opened in run.save_gmtk_output() to this function. This change doesn't work in the case of multiple genomedata archives. I removed the \"genome\" argument from observations.save() (as well as from observations,write() ). Instead, I opened the Genomedata object within observations.write(), in the part of the code that computes tracks_means and tracks_vars for the purpose of computing zscores. This change should make the code work with multiple genomedata archives again. It's possible it still doesn't work with concatenated input (i.e. multiple worlds) -- you may want to test that.", "markup": "markdown", "html": "<p>@rcwchan : </p>\n<p>I made some changes that should fix this patch in the case of multiple genomedata archives. Unfortunately, after about 30 minutes of messing with my environment, I could not get this version of Segway working, so I haven't tested these changes. There are almost certainly bugs -- if you're having trouble fixing them, let me know and I'll try to help.</p>\n<p>Briefly, here is what I did: The previous patch changed observations.save() to take a Genomedata object as input, and passed the genomedata object opened in run.save_gmtk_output() to this function. This change doesn't work in the case of multiple genomedata archives. I removed the \"genome\" argument from observations.save() (as well as from observations,write() ). Instead, I opened the Genomedata object within observations.write(), in the part of the code that computes tracks_means and tracks_vars for the purpose of computing zscores. This change should make the code work with multiple genomedata archives again. It's possible it still doesn't work with concatenated input (i.e. multiple worlds) -- you may want to test that.</p>", "type": "rendered"}, "created_on": "2016-07-03T02:18:00.055969+00:00", "user": {"display_name": "mlibbrecht", "uuid": "{5386772a-11f2-40a6-922a-1557e4210ce0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5386772a-11f2-40a6-922a-1557e4210ce0%7D"}, "html": {"href": "https://bitbucket.org/%7B5386772a-11f2-40a6-922a-1557e4210ce0%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4f04fb35d1668084963524c0e908eac9d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsM-5.png"}}, "nickname": "mlibbrecht", "type": "user", "account_id": "557058:1c71e8bb-defa-4b90-b75b-f9517c35ceb8"}, "updated_on": "2016-07-03T02:18:00.065236+00:00", "type": "pullrequest_comment", "id": 20533656}