{"links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/6/comments/2412485.json"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/6/_/diff#comment-2412485"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 6, "links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/6.json"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/6"}}, "title": "Moved assertion to prevent error in semi supervised mode"}, "content": {"raw": "I ran test_all.sh (so all tests under unsupervised mode) and they all passed as before. Running simpleseg with semi-supervised mode passed the train task with no errors, and caused what I believe is a known error with semi-supervised mode in the identify task (can be found searching \"supervisionLabel\" in segway internal email archives):\n\n```\nERROR: discrete observed random variable 'supervisionLabel', frame 0, line 79, specifies a feature element 4:4 that is out of discrete range ([2:3] inclusive) of observation matrix\nTraceback (most recent call last):\n  File \"/mnt/work1/users/home2/ashaw/bin/segway-task\", line 9, in <module>\n    load_entry_point('segway==1.2.0.dev-rel882-hge5c01c41a55fp', 'console_scripts', 'segway-task')()\n  File \"/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/task.py\", line 387, in main\n    return task(*args)\n  File \"/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/task.py\", line 379, in task\n    outfilename, *args)\n  File \"/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/task.py\", line 350, in run_viterbi_save_bed\n    output = VITERBI_PROG.getoutput(*args)\n  File \"/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py\", line 206, in getoutput\n    return self._getoutput(args, kwargs, stdout=PIPE)\n  File \"/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py\", line 194, in _getoutput\n    stdin, stdout, stderr, cwd)\n  File \"/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py\", line 157, in _popen\n    _returncode_error_factory(cmdline, returncode, output, error)\n  File \"/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py\", line 57, in _returncode_error_factory\n    raise error_cls, (cmdline, returncode, output, error)\noptbuild.ReturncodeError: /mnt/work1/users/home2/ashaw/bin/gmtkViterbi returned 1\n```\nThis was the behavior for me before the change as well, when I disabled the previous assertion check to allow segway to progress in semi-supervised mode. This error can be avoided by passing the identify task a copy of the generated segway.str with the supervisionLabel variables removed (again, true before and after the change). When I do this, the test fails (since semi-supervised changes the behavior) but it finishes with no error (nothing in \\*/output/e/\\*).\n\nFinally, I ran in unsupervised mode, but with a user track named \"supervisionLabel\" to make sure that is still not allowed, and it failed the assertion as expected:\n\n```\nTraceback (most recent call last):\n  File \"/mnt/work1/users/home2/ashaw/bin/segway\", line 9, in <module>\n    load_entry_point('segway==1.2.0.dev-rel882-hge5c01c41a55fp', 'console_scripts', 'segway')()\n  File \"/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/run.py\", line 2532, in main\n    runner = Runner.fromoptions(args, options)\n  File \"/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/run.py\", line 737, in fromoptions\n    res.add_track_group(track_spec.split(\",\"))\n  File \"/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/run.py\", line 687, in add_track_group\n    assert \"supervisionLabel\" not in tracknames\nAssertionError\n```", "markup": "markdown", "html": "<p>I ran test_all.sh (so all tests under unsupervised mode) and they all passed as before. Running simpleseg with semi-supervised mode passed the train task with no errors, and caused what I believe is a known error with semi-supervised mode in the identify task (can be found searching \"supervisionLabel\" in segway internal email archives):</p>\n<div class=\"codehilite\"><pre><span></span><span class=\"n\">ERROR</span><span class=\"o\">:</span> <span class=\"n\">discrete</span> <span class=\"n\">observed</span> <span class=\"n\">random</span> <span class=\"n\">variable</span> <span class=\"s1\">&#39;supervisionLabel&#39;</span><span class=\"o\">,</span> <span class=\"n\">frame</span> <span class=\"mi\">0</span><span class=\"o\">,</span> <span class=\"n\">line</span> <span class=\"mi\">79</span><span class=\"o\">,</span> <span class=\"n\">specifies</span> <span class=\"n\">a</span> <span class=\"n\">feature</span> <span class=\"n\">element</span> <span class=\"mi\">4</span><span class=\"o\">:</span><span class=\"mi\">4</span> <span class=\"n\">that</span> <span class=\"k\">is</span> <span class=\"n\">out</span> <span class=\"n\">of</span> <span class=\"n\">discrete</span> <span class=\"n\">range</span> <span class=\"o\">([</span><span class=\"mi\">2</span><span class=\"o\">:</span><span class=\"mi\">3</span><span class=\"o\">]</span> <span class=\"n\">inclusive</span><span class=\"o\">)</span> <span class=\"n\">of</span> <span class=\"n\">observation</span> <span class=\"n\">matrix</span>\n<span class=\"n\">Traceback</span> <span class=\"o\">(</span><span class=\"n\">most</span> <span class=\"n\">recent</span> <span class=\"n\">call</span> <span class=\"n\">last</span><span class=\"o\">):</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/ashaw/bin/segway-task&quot;</span><span class=\"o\">,</span> <span class=\"n\">line</span> <span class=\"mi\">9</span><span class=\"o\">,</span> <span class=\"k\">in</span> <span class=\"o\">&lt;</span><span class=\"n\">module</span><span class=\"o\">&gt;</span>\n    <span class=\"n\">load_entry_point</span><span class=\"o\">(</span><span class=\"s1\">&#39;segway==1.2.0.dev-rel882-hge5c01c41a55fp&#39;</span><span class=\"o\">,</span> <span class=\"s1\">&#39;console_scripts&#39;</span><span class=\"o\">,</span> <span class=\"s1\">&#39;segway-task&#39;</span><span class=\"o\">)()</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/task.py&quot;</span><span class=\"o\">,</span> <span class=\"n\">line</span> <span class=\"mi\">387</span><span class=\"o\">,</span> <span class=\"k\">in</span> <span class=\"n\">main</span>\n    <span class=\"k\">return</span> <span class=\"n\">task</span><span class=\"o\">(*</span><span class=\"n\">args</span><span class=\"o\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/task.py&quot;</span><span class=\"o\">,</span> <span class=\"n\">line</span> <span class=\"mi\">379</span><span class=\"o\">,</span> <span class=\"k\">in</span> <span class=\"n\">task</span>\n    <span class=\"n\">outfilename</span><span class=\"o\">,</span> <span class=\"o\">*</span><span class=\"n\">args</span><span class=\"o\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/task.py&quot;</span><span class=\"o\">,</span> <span class=\"n\">line</span> <span class=\"mi\">350</span><span class=\"o\">,</span> <span class=\"k\">in</span> <span class=\"n\">run_viterbi_save_bed</span>\n    <span class=\"n\">output</span> <span class=\"o\">=</span> <span class=\"n\">VITERBI_PROG</span><span class=\"o\">.</span><span class=\"na\">getoutput</span><span class=\"o\">(*</span><span class=\"n\">args</span><span class=\"o\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py&quot;</span><span class=\"o\">,</span> <span class=\"n\">line</span> <span class=\"mi\">206</span><span class=\"o\">,</span> <span class=\"k\">in</span> <span class=\"n\">getoutput</span>\n    <span class=\"k\">return</span> <span class=\"n\">self</span><span class=\"o\">.</span><span class=\"na\">_getoutput</span><span class=\"o\">(</span><span class=\"n\">args</span><span class=\"o\">,</span> <span class=\"n\">kwargs</span><span class=\"o\">,</span> <span class=\"n\">stdout</span><span class=\"o\">=</span><span class=\"n\">PIPE</span><span class=\"o\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py&quot;</span><span class=\"o\">,</span> <span class=\"n\">line</span> <span class=\"mi\">194</span><span class=\"o\">,</span> <span class=\"k\">in</span> <span class=\"n\">_getoutput</span>\n    <span class=\"n\">stdin</span><span class=\"o\">,</span> <span class=\"n\">stdout</span><span class=\"o\">,</span> <span class=\"n\">stderr</span><span class=\"o\">,</span> <span class=\"n\">cwd</span><span class=\"o\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py&quot;</span><span class=\"o\">,</span> <span class=\"n\">line</span> <span class=\"mi\">157</span><span class=\"o\">,</span> <span class=\"k\">in</span> <span class=\"n\">_popen</span>\n    <span class=\"n\">_returncode_error_factory</span><span class=\"o\">(</span><span class=\"n\">cmdline</span><span class=\"o\">,</span> <span class=\"n\">returncode</span><span class=\"o\">,</span> <span class=\"n\">output</span><span class=\"o\">,</span> <span class=\"n\">error</span><span class=\"o\">)</span>\n  <span class=\"n\">File</span> <span class=\"s2\">&quot;/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py&quot;</span><span class=\"o\">,</span> <span class=\"n\">line</span> <span class=\"mi\">57</span><span class=\"o\">,</span> <span class=\"k\">in</span> <span class=\"n\">_returncode_error_factory</span>\n    <span class=\"n\">raise</span> <span class=\"n\">error_cls</span><span class=\"o\">,</span> <span class=\"o\">(</span><span class=\"n\">cmdline</span><span class=\"o\">,</span> <span class=\"n\">returncode</span><span class=\"o\">,</span> <span class=\"n\">output</span><span class=\"o\">,</span> <span class=\"n\">error</span><span class=\"o\">)</span>\n<span class=\"n\">optbuild</span><span class=\"o\">.</span><span class=\"na\">ReturncodeError</span><span class=\"o\">:</span> <span class=\"sr\">/mnt/work1/users/home2/ashaw/bin/g</span><span class=\"n\">mtkViterbi</span> <span class=\"n\">returned</span> <span class=\"mi\">1</span>\n</pre></div>\n\n\n<p>This was the behavior for me before the change as well, when I disabled the previous assertion check to allow segway to progress in semi-supervised mode. This error can be avoided by passing the identify task a copy of the generated segway.str with the supervisionLabel variables removed (again, true before and after the change). When I do this, the test fails (since semi-supervised changes the behavior) but it finishes with no error (nothing in */output/e/*).</p>\n<p>Finally, I ran in unsupervised mode, but with a user track named \"supervisionLabel\" to make sure that is still not allowed, and it failed the assertion as expected:</p>\n<div class=\"codehilite\"><pre><span></span>Traceback (most recent call last):\n  File &quot;/mnt/work1/users/home2/ashaw/bin/segway&quot;, line 9, in &lt;module&gt;\n    load_entry_point(&#39;segway==1.2.0.dev-rel882-hge5c01c41a55fp&#39;, &#39;console_scripts&#39;, &#39;segway&#39;)()\n  File &quot;/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/run.py&quot;, line 2532, in main\n    runner = Runner.fromoptions(args, options)\n  File &quot;/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/run.py&quot;, line 737, in fromoptions\n    res.add_track_group(track_spec.split(&quot;,&quot;))\n  File &quot;/mnt/work1/users/home2/ashaw/bin/lib/python2.7/site-packages/segway-1.2.0.dev_rel882_hge5c01c41a55fp-py2.7.egg/segway/run.py&quot;, line 687, in add_track_group\n    assert &quot;supervisionLabel&quot; not in tracknames\nAssertionError\n</pre></div>", "type": "rendered"}, "created_on": "2014-07-15T16:41:21.527887+00:00", "user": {"display_name": "ajshaw", "uuid": "{547650d6-1225-4731-b1da-ba9913babfbf}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B547650d6-1225-4731-b1da-ba9913babfbf%7D"}, "html": {"href": "https://bitbucket.org/%7B547650d6-1225-4731-b1da-ba9913babfbf%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1f9b227ab720d7a41f4f0d49570db03fd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsA-2.png"}}, "nickname": "ajshaw", "type": "user", "account_id": "5b22d060ba383e0814004a64"}, "updated_on": "2014-07-15T16:41:21.544306+00:00", "type": "pullrequest_comment", "id": 2412485}