{"changes": {"content": {"new": "While running segway on recovery (training mode), I received this error:\r\n\r\n\r\n```\r\n#!python\r\n\r\nTraceback (most recent call last):\r\n   File \"/mnt/work1/users/home2/rachelc/.local/bin/segway\", line 9, in <module>\r\n     load_entry_point('segway==1.4.1.dev0'", "old": "While running segway on recovery (training mode), I received this error:\r\n\r\n```Traceback (most recent call last):\r\n   File \"/mnt/work1/users/home2/rachelc/.local/bin/segway\", line 9, in <module>\r\n     load_entry_point('segway==1.4.1.dev0', 'console_scrip"}}, "links": {"self": {"href": "data/repositories/hoffmanlab/segway/issues/67/changes/28103423.json"}, "html": {"href": "#!/hoffmanlab/segway/issues/67#comment-28103423"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway/issues/67.json"}}, "type": "issue", "id": 67, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "title": "segway recovery (training mode) fails to copy over likelihood files"}, "created_on": "2016-05-27T17:15:04.253469+00:00", "user": {"display_name": "Rachel Chan", "uuid": "{20430f8d-4e6b-48cc-a8d8-c64868bf7e79}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D"}, "html": {"href": "https://bitbucket.org/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4397abec9f84e35f1f235b350984833dd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsRC-1.png"}}, "nickname": "rcwchan", "type": "user", "account_id": "557058:e439e22e-8cfc-4cf1-b090-030d33a0730e"}, "message": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "type": "issue_change", "id": 28103423}