{"links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/54/comments/20117135.json"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/diff/rcwchan/segway:6b2199aaa4ae..02c1669515d6?path=segway%2Fcluster%2F__init__.py"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/54/_/diff#comment-20117135"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 54, "links": {"self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/54.json"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/54"}}, "title": "Add job template deletion to cluster/common.py and cluster/__init__.py"}, "content": {"raw": "This passed all the simple* tests both locally and on mordor, but I decided to try it out with a larger run just in case. Just got this error:\n\n```\n207 critical error: error: lGetElemStr(Nameindex = 1400): run time type error\n208 Exception in thread Thread-1:\n209 Traceback (most recent call last):\n210   File \"/mnt/work1/software/python/2.7/lib/python2.7/threading.py\", line 551, in __bootstrap_inner\n211     self.run()\n212   File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 438, in run\n213     self.result = self.runner.run_train_instance()\n214   File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2133, in run_train_instance\n215     round_index, kwargs)\n216   File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2140, in progress_train_instance\n217     self.run_train_round(self.instance_index, round_index, **kwargs)\n218   File \"/mnt/work1/users/home2/rachelc/segway/segway/run.py\", line 2092, in run_train_round\n219     restartable_jobs.wait()\n220   File \"/mnt/work1/users/home2/rachelc/segway/segway/cluster/__init__.py\", line 292, in wait\n221     self.process_job(jobid, job_info)\n222   File \"/mnt/work1/users/home2/rachelc/segway/segway/cluster/__init__.py\", line 254, in process_job\n223     jobname = restartable_job.job_tmpl_factory.template.jobName\n224   File \"/mnt/work1/users/home2/rachelc/.local/lib/python2.7/site-packages/drmaa/helpers.py\", line 159, in __get__\n225     sizeof(attr_buffer))\n226   File \"/mnt/work1/users/home2/rachelc/.local/lib/python2.7/site-packages/drmaa/helpers.py\", line 299, in c\n227     return f(*(args + (error_buffer, sizeof(error_buffer))))\n228   File \"/mnt/work1/users/home2/rachelc/.local/lib/python2.7/site-packages/drmaa/errors.py\", line 151, in error_check\n229     raise _ERRORS[code - 1](error_string)\n230 InvalidAttributeValueException: code 14: The value for the job attribute is invalid.\n```\n\nthink it might be because the job template is being deleted before all references to the RestartableJob are gone. However, there doesn't seem to be any other place in the code where the RestartableJob is deleted explicitly, so I don't know where I would put this function call. @ericr86 , where do you think would be a good place to call this?\n\nEDIT: can confirm error is caused by premature template deletion; errors (same error appears multiple times) go away after reverting back to using the ```__del__``` function.", "markup": "markdown", "html": "<p>This passed all the simple* tests both locally and on mordor, but I decided to try it out with a larger run just in case. Just got this error:</p>\n<div class=\"codehilite\"><pre><span></span>207 critical error: error: lGetElemStr(Nameindex = 1400): run time type error\n208 Exception in thread Thread-1:\n209 Traceback (most recent call last):\n210   File &quot;/mnt/work1/software/python/2.7/lib/python2.7/threading.py&quot;, line 551, in __bootstrap_inner\n211     self.run()\n212   File &quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;, line 438, in run\n213     self.result = self.runner.run_train_instance()\n214   File &quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;, line 2133, in run_train_instance\n215     round_index, kwargs)\n216   File &quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;, line 2140, in progress_train_instance\n217     self.run_train_round(self.instance_index, round_index, **kwargs)\n218   File &quot;/mnt/work1/users/home2/rachelc/segway/segway/run.py&quot;, line 2092, in run_train_round\n219     restartable_jobs.wait()\n220   File &quot;/mnt/work1/users/home2/rachelc/segway/segway/cluster/__init__.py&quot;, line 292, in wait\n221     self.process_job(jobid, job_info)\n222   File &quot;/mnt/work1/users/home2/rachelc/segway/segway/cluster/__init__.py&quot;, line 254, in process_job\n223     jobname = restartable_job.job_tmpl_factory.template.jobName\n224   File &quot;/mnt/work1/users/home2/rachelc/.local/lib/python2.7/site-packages/drmaa/helpers.py&quot;, line 159, in __get__\n225     sizeof(attr_buffer))\n226   File &quot;/mnt/work1/users/home2/rachelc/.local/lib/python2.7/site-packages/drmaa/helpers.py&quot;, line 299, in c\n227     return f(*(args + (error_buffer, sizeof(error_buffer))))\n228   File &quot;/mnt/work1/users/home2/rachelc/.local/lib/python2.7/site-packages/drmaa/errors.py&quot;, line 151, in error_check\n229     raise _ERRORS[code - 1](error_string)\n230 InvalidAttributeValueException: code 14: The value for the job attribute is invalid.\n</pre></div>\n\n\n<p>think it might be because the job template is being deleted before all references to the RestartableJob are gone. However, there doesn't seem to be any other place in the code where the RestartableJob is deleted explicitly, so I don't know where I would put this function call. @ericr86 , where do you think would be a good place to call this?</p>\n<p>EDIT: can confirm error is caused by premature template deletion; errors (same error appears multiple times) go away after reverting back to using the <code>__del__</code> function.</p>", "type": "rendered"}, "created_on": "2016-06-22T22:02:38.893282+00:00", "user": {"display_name": "Rachel Chan", "uuid": "{20430f8d-4e6b-48cc-a8d8-c64868bf7e79}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D"}, "html": {"href": "https://bitbucket.org/%7B20430f8d-4e6b-48cc-a8d8-c64868bf7e79%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4397abec9f84e35f1f235b350984833dd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsRC-1.png"}}, "nickname": "rcwchan", "type": "user", "account_id": "557058:e439e22e-8cfc-4cf1-b090-030d33a0730e"}, "inline": {"to": 274, "from": null, "outdated": true, "path": "segway/cluster/__init__.py"}, "updated_on": "2016-06-22T22:20:48.270555+00:00", "type": "pullrequest_comment", "id": 20117135}