{"links": {"self": {"href": "data/repositories/hoffmanlab/segway/issues/114/comments/38570438.json"}, "html": {"href": "#!/hoffmanlab/segway/issues/114#comment-38570438"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway/issues/114.json"}}, "type": "issue", "id": 114, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "title": "Standard output not being captured"}, "content": {"raw": "I suspect since it was just changing training to be submitted as a task, and that stderr is captured correctly, that the same mechanism used for stderr should be used for stdout and should have been updated with this change but wasn't.", "markup": "markdown", "html": "<p>I suspect since it was just changing training to be submitted as a task, and that stderr is captured correctly, that the same mechanism used for stderr should be used for stdout and should have been updated with this change but wasn't.</p>", "type": "rendered"}, "created_on": "2017-07-26T14:43:11.871403+00:00", "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "updated_on": null, "type": "issue_comment", "id": 38570438}